#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://docs.travis-ci.com/user/languages/php/ for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

php: [7.2, 7.3, 7.4]

matrix:
    allow_failures:	
        - php: 7.4
    fast_finish: true

script:
  # PHP lint
  - >
    echo;
    echo "Running PHP lint";
    find . -path ./vendor -prune -o -type f -name '*.php' ! -name "test_with_parse_error.php" -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
  # start PHP5.4 built-in server in background
  - nohup php -S localhost:8080 -t test/site > php-server.log 2>&1 &
  - php test/all_tests.php
  - cat php-server.log

# disable notifications
notifications:
  email: false

# reduce commit history of git checkout
git:
  depth: 5
