<?php
    // $Id$
    
    /**
     *    Carries the reporter around the test suite.
     *    This runner is teh simplest possible, just passing
     *    each result in turn to the test suite.
     */
    class TestRunner {
        var $_reporter;
        var $_status;
        
        /**
         *    Sets up an reporter to receive events.
         */
        function TestRunner(&$reporter) {
            $this->_reporter = &$reporter;
            $this->_status = true;
        }
        
        /**
         *    Hook for invoking the actual test method.
         *    @param SimpleTest $test_case    The test case method to call.
         *    @param string $method           Method name to invoke.
         *    @access public
         */
        function invoke(&$test_case, $method) {
            $test_case->invoke($this, $method);
        }
        
        /**
         *    Pass event handler. Generated by a successful
         *    assertion.
         *    @param string $message        Message to display.
         *    @access public
         */
        function handlePass($message) {
            $this->_reporter->paintPass($message);
        }
        
        /**
         *    Fail event handler. Generated by a failed
         *    assertion.
         *    @param string $message        Message to display.
         *    @access public
         */
        function handleFail($message) {
            $this->_reporter->paintFail($message);
            $this->_status = false;
        }
        
        /**
         *    Deals with PHP 4 throwing an error.
         *    @param string $message    Text of error formatted by
         *                              the test case.
         *    @access public
         */
        function handleError($message) {
            $this->_reporter->paintException($message);
            $this->_status = false;
        }
        
        /**
         *    Deals with PHP 5 throwing an exception
         *    This isn't really implemented yet.
         *    @param Exception $exception     Object thrown.
         *    @access public
         */
        function handleException($exception) {
            $this->_reporter->paintException("Unexpected exception");
            $this->_status = false;
        }
        
        /**
         *    Sends a simple message to the reporter.
         *    @param string $message        Message to display.
         *    @access public
         */
        function handleMessage($message) {
            $this->_reporter->paintMessage($message);
        }
        
        /**
         *    Sends a formatted ASCII message to the reporter.
         *    @param string $message        Message to display.
         *    @access public
         */
        function handleFormattedMessage($message) {
            $this->_reporter->paintFormattedMessage($message);
        }
        
        /**
         *    Start of a test method.
         *    @param string $method        Test method name.
         *    @access public
         */
        function handleMethodStart($method) {
            $this->_reporter->paintStart($method, 0);
        }
        
        /**
         *    End of a test method.
         *    @param string $method        Test method name.
         *    @access public
         */
        function handleMethodEnd($method) {
            $this->_reporter->paintEnd($method, 0);
        }
        
        /**
         *    Start of a test case with test methods
         *    only. Reports only one internal test case.
         *    @param string $label        Test case name.
         *    @access public
         */
        function handleCaseStart($label) {
            $this->_reporter->paintStart($label, 1);
        }
        
        /**
         *    End of a test case with test methods
         *    only. Reports one test case completed.
         *    @param string $label        Test case name.
         *    @access public
         */
        function handleCaseEnd($label) {
            $this->_reporter->paintEnd($label, 1);
        }
        
        /**
         *    Start of a group test with held cases.
         *    @param string $label         Test case name.
         *    @param integer $size         Number of test cases held.
         *    @access public
         */
        function handleGroupStart($label, $size) {
            $this->_reporter->paintStart($label, $size);
        }
        
        /**
         *    End of a group test with held cases.
         *    @param string $label        Test case name.
         *    @access public
         */
        function handleGroupEnd($label) {
            $this->_reporter->paintEnd($label, 0);
        }
        
        /**
         *    A user event. Can be used for ad hoc
         *    expansion of the toolkit. Default is
         *    to just pass it through to the display.
         *    @param string $type     Event type as text.
         *    @param mixed $payload   Message or other data.
         *    @return boolean         False on failure.
         *    @access public
         */
        function handleSignal($type, &$payload) {
            if (! $this->_reporter->paintSignal($type, $payload)) {
                $this->_status = false;
            }
        }
        
        /**
         *    Accessor for current status. Will be false
         *    if there have been any failures or exceptions.
         *    Used for command line tools.
         *    @return boolean        True if no failures.
         */
        function getStatus() {
            return $this->_status;
        }
    }
    
    /**
     *    Can recieve test events and display them. Display
     *    is achieved by making display methods available
     *    and visiting the incoming event. Abstract.
     */
    class TestReporter {
        
        /**
         *    Does nothing.
         *    @access public
         */
        function TestReporter() {
        }
        
        /**
         *    Paints the start of a test.
         *    @param string $test_name     Name of test or other label.
         *    @param integer $size         Number of test cases starting.
         *    @access public
         */
        function paintStart($test_name, $size) {
        }
        
        /**
         *    Paints the end of a test.
         *    @param string $test_name     Name of test or other label.
         *    @param integer $progress     Number of cases just finished.
         *    @access public
         */
        function paintEnd($test_name, $progress) {
        }
        
        /**
         *    Paints a pass. This will often output nothing.
         *    @param string $message        Passing message.
         *    @access public
         */
        function paintPass($message) {
        }
        
        /**
         *    Paints a failure.
         *    @param string $message        Failure message from test.
         *    @access public
         */
        function paintFail($message) {
        }
        
        /**
         *    Paints a simple supplementary message.
         *    @param string $message        Text to display.
         *    @access public
         */
        function paintMessage($message) {
        }
        
        /**
         *    Paints a formatted ASCII message such as a
         *    variable dump.
         *    @param string $message        Text to display.
         *    @access public
         */
        function paintFormattedMessage($message) {
        }
        
        /**
         *    By default just ignores user generated
         *    events.
         *    @param string $type        Event type as text.
         *    @param mixed $payload      Message or object.
         *    @return boolean            Should return false if this
         *                               type of signal should fail the
         *                               test suite.
         *    @access public
         */
        function paintSignal($type, &$payload) {
            return true;
        }
    }
    
    /**
     *    Recipient of generated test messages that can display
     *    page footers and headers. Also keeps track of the
     *    test nesting. This is the main base class on which
     *    to build the finished test (page based) displays.
     */
    class TestDisplay extends TestReporter {
        var $_test_stack;
        var $_passes;
        var $_fails;
        var $_exceptions;
        var $_size;
        var $_progress;
        
        /**
         *    Starts the display with no results in.
         *    @access public
         */
        function TestDisplay() {
            $this->TestReporter();
            $this->_test_stack = array();
            $this->_passes = 0;
            $this->_fails = 0;
            $this->_exceptions = 0;
            $this->_size = null;
            $this->_progress = 0;
        }
        
        /**
         *    Paints the start of a test. Will also paint
         *    the page header and footer if this is the
         *    first test. Will stash the size if the first
         *    start.
         *    @param string $test_name   Name of test that is starting.
         *    @param integer $size       Number of test cases starting.
         *    @access public
         */
        function paintStart($test_name, $size) {
            if (!isset($this->_size)) {
                $this->_size = $size;
            }
            if (count($this->_test_stack) == 0) {
                $this->paintHeader($test_name);
            }
            $this->_test_stack[] = $test_name;
        }
        
        /**
         *    Paints the end of a test. Will paint the page
         *    footer if the stack of tests has unwound.
         *    @param string $test_name   Name of test that is ending.
         *    @param integer $progress   Number of test cases ending.
         *    @access public
         */
        function paintEnd($test_name, $progress) {
            $this->_progress += $progress;
            array_pop($this->_test_stack);
            if (count($this->_test_stack) == 0) {
                $this->paintFooter($test_name);
            }
        }
        
        /**
         *    Increments the pass count.
         *    @param string $message        Message is ignored.
         *    @access public
         */
        function paintPass($message) {
            $this->_passes++;
        }
        
        /**
         *    Increments the fail count.
         *    @param string $message        Message is ignored.
         *    @access public
         */
        function paintFail($message) {
            $this->_fails++;
        }
        
        /**
         *    Paints a PHP error or exception.
         *    @param string $message        Message is ignored.
         *    @access public
         *    @abstract
         */
        function paintException($message) {
            $this->_exceptions++;
        }
        
        /**
         *    Paints the test document header.
         *    @param string $test_name     First test top level
         *                                 to start.
         *    @access public
         *    @abstract
         */
        function paintHeader($test_name) {
        }
        
        /**
         *    Paints the test document footer.
         *    @param string $test_name        The top level test.
         *    @access public
         *    @abstract
         */
        function paintFooter($test_name) {
        }
        
        /**
         *    Accessor for internal test stack. For
         *    subclasses that need to see the whole test
         *    history for display purposes.
         *    @return array     List of methods in nesting order.
         *    @access public
         */
        function getTestList() {
            return $this->_test_stack;
        }
        
        /**
         *    Accessor for the number of passes so far.
         *    @return integer       Number of passes.
         *    @access public
         */
        function getPassCount() {
            return $this->_passes;
        }
        
        /**
         *    Accessor for the number of fails so far.
         *    @return integer       Number of fails.
         *    @access public
         */
        function getFailCount() {
            return $this->_fails;
        }
        
        /**
         *    Accessor for the number of untrapped errors
         *    so far.
         *    @return integer       Number of exceptions.
         *    @access public
         */
        function getExceptionCount() {
            return $this->_exceptions;
        }
        
        /**
         *    Accessor for total test size in number
         *    of test cases. Null until the first
         *    test is started.
         *    @return integer   Total number of cases at start.
         *    @access public
         */
        function getTestCaseCount() {
            return $this->_size;
        }
        
        /**
         *    Accessor for the number of test cases
         *    completed so far.
         *    @return integer   Number of ended cases.
         *    @access public
         */
        function getTestCaseProgress() {
            return $this->_progress;
        }
    }
?>