<?php
    // $Id$
    
    if (!defined("SIMPLE_TEST")) {
        define("SIMPLE_TEST", "./");
    }

    /**
     *    Carries the reporter around the test suite.
     */
    class TestRunner {
        var $_reporter;
        
        /**
         *    Sets up an reporter to receive events.
         */
        function TestRunner(&$reporter) {
            $this->_reporter = &$reporter;
        }
        
        /**
         *    Hook for invoking the actual test method.
         */
        function invoke(&$test_case, $method) {
            $test_case->invoke($this, $method);
        }
        
        /**
         *    Pass event handler. Generated by a successful
         *    assertion.
         *    @param $message        Message to display.
         *    @public
         */
        function handlePass($message) {
            $this->_reporter->paintPass($message);
        }
        
        /**
         *    Fail event handler. Generated by a failed
         *    assertion.
         *    @param $message        Message to display.
         *    @public
         */
        function handleFail($message) {
            $this->_reporter->paintFail($message);
        }
        
        /**
         *    Deals with PHP 4 throwing an error.
         *    @param $message    Text of error formatted by
         *                       the test case.
         *    @public
         */
        function handleError($message) {
            $this->_reporter->paintException($message);
        }
        
        /**
         *    Deals with PHP 5 throwing an exception
         *    This isn't really implemented yet.
         *    @param $exception     Exception object thrown.
         *    @public
         */
        function handleException($exception) {
            $this->_reporter->paintException("Unexpected exception");
        }
        
        /**
         *    Sends a simple message to the reporter.
         *    @param $message        Message to display.
         *    @public
         */
        function handleMessage($message) {
            $this->_reporter->paintMessage($message);
        }
        
        /**
         *    Sends a formatted ASCII message to the reporter.
         *    @param $message        Message to display.
         *    @public
         */
        function handleFormattedMessage($message) {
            $this->_reporter->paintFormattedMessage($message);
        }
        
        /**
         *    Start of a test method.
         *    @param $method        Test method name.
         *    @public
         */
        function handleMethodStart($method) {
            $this->_reporter->paintStart($method, 0);
        }
        
        /**
         *    End of a test method.
         *    @param $method        Test method name.
         *    @public
         */
        function handleMethodEnd($method) {
            $this->_reporter->paintEnd($method, 0);
        }
        
        /**
         *    Start of a test case with test methods
         *    only. Reports only one internal test case.
         *    @param $label        Test case name.
         *    @public
         */
        function handleCaseStart($label) {
            $this->_reporter->paintStart($label, 1);
        }
        
        /**
         *    End of a test case with test methods
         *    only. Reports one test case completed.
         *    @param $label        Test case name.
         *    @public
         */
        function handleCaseEnd($label) {
            $this->_reporter->paintEnd($label, 1);
        }
        
        /**
         *    Start of a group test with held cases.
         *    @param $label        Test case name.
         *    @param $size         Number of test cases held.
         *    @public
         */
        function handleGroupStart($label, $size) {
            $this->_reporter->paintStart($label, $size);
        }
        
        /**
         *    End of a group test with held cases.
         *    @param $label        Test case name.
         *    @public
         */
        function handleGroupEnd($label) {
            $this->_reporter->paintEnd($label, 0);
        }
    }
    
    /**
     *    Can recieve test events and display them. Display
     *    is achieved by making display methods available
     *    and visiting the incoming event. Abstract.
     */
    class TestReporter {
        
        /**
         *    Does nothing.
         *    @public
         */
        function TestReporter() {
        }
        
        /**
         *    Paints the start of a test.
         *    @param $test_name     Name of test or other label.
         *    @param $size          Number of test cases starting.
         *    @public
         */
        function paintStart($test_name, $size) {
        }
        
        /**
         *    Paints the end of a test.
         *    @param $test_name     Name of test or other label.
         *    @param $progress      Number of cases just finished.
         *    @public
         */
        function paintEnd($test_name, $progress) {
        }
        
        /**
         *    Paints a pass. This will often output nothing.
         *    @param $message        Passing message.
         *    @public
         */
        function paintPass($message) {
        }
        
        /**
         *    Paints a failure.
         *    @param $message        Failure message from test.
         *    @public
         */
        function paintFail($message) {
        }
        
        /**
         *    Paints a simple supplementary message.
         *    @param $message        Text to display.
         *    @public
         */
        function paintMessage($message) {
        }
        
        /**
         *    Paints a formatted ASCII message such as a
         *    variable dump.
         *    @param $message        Text to display.
         *    @public
         */
        function paintFormattedMessage($message) {
        }
    }
    
    /**
     *    Recipient of generated test messages that can display
     *    page footers and headers. Also keeps track of the
     *    test nesting. This is the main base class on which
     *    to build the finished test (page based) displays.
     */
    class TestDisplay extends TestReporter {
        var $_test_stack;
        var $_passes;
        var $_fails;
        var $_exceptions;
        var $_size;
        var $_progress;
        
        /**
         *    Starts the display with no results in.
         *    @public
         */
        function TestDisplay() {
            $this->TestReporter();
            $this->_test_stack = array();
            $this->_passes = 0;
            $this->_fails = 0;
            $this->_exceptions = 0;
            $this->_size = null;
            $this->_progress = 0;
        }
        
        /**
         *    Paints the start of a test. Will also paint
         *    the page header and footer if this is the
         *    first test. Will stash the size if the first
         *    start.
         *    @param $test_name   Name of test that is starting.
         *    @param $size        Number of test cases starting.
         *    @public
         */
        function paintStart($test_name, $size) {
            if (!isset($this->_size)) {
                $this->_size = $size;
            }
            if (count($this->_test_stack) == 0) {
                $this->paintHeader($test_name);
            }
            $this->_test_stack[] = $test_name;
        }
        
        /**
         *    Paints the end of a test. Will paint the page
         *    footer if the stack of tests has unwound.
         *    @param $test_name   Name of test that is ending.
         *    @param $progress    Number of test cases ending.
         *    @public
         */
        function paintEnd($test_name, $progress) {
            $this->_progress += $progress;
            array_pop($this->_test_stack);
            if (count($this->_test_stack) == 0) {
                $this->paintFooter($test_name);
            }
        }
        
        /**
         *    Increments the pass count.
         *    @param $message        Message is ignored.
         *    @public
         */
        function paintPass($message) {
            $this->_passes++;
        }
        
        /**
         *    Increments the fail count.
         *    @param $message        Message is ignored.
         *    @public
         */
        function paintFail($message) {
            $this->_fails++;
        }
        
        /**
         *    Paints a PHP error or exception.
         *    @param $message        Message is ignored.
         *    @public
         *    @abstract
         */
        function paintException($message) {
            $this->_exceptions++;
        }
        
        /**
         *    Paints the test document header.
         *    @param $test_name        First test top level
         *                             to start.
         *    @public
         *    @abstract
         */
        function paintHeader($test_name) {
        }
        
        /**
         *    Paints the test document footer.
         *    @param $test_name        The top level test.
         *    @public
         *    @abstract
         */
        function paintFooter($test_name) {
        }
        
        /**
         *    Accessor for internal test stack. For
         *    subclasses that need to see the whole test
         *    history for display purposes.
         *    @return      List of methods in nesting order.
         *    @public
         */
        function getTestList() {
            return $this->_test_stack;
        }
        
        /**
         *    Accessor for the number of passes so far.
         *    @return        Number of passes.
         *    @public
         */
        function getPassCount() {
            return $this->_passes;
        }
        
        /**
         *    Accessor for the number of fails so far.
         *    @return        Number of fails.
         *    @public
         */
        function getFailCount() {
            return $this->_fails;
        }
        
        /**
         *    Accessor for the number of untrapped errors
         *    so far.
         *    @return        Number of exceptions.
         *    @public
         */
        function getExceptionCount() {
            return $this->_exceptions;
        }
        
        /**
         *    Accessor for total test size in number
         *    of test cases. Null until the first
         *    test is started.
         *    @return    Total number of cases at start.
         *    @public
         */
        function getTestCaseCount() {
            return $this->_size;
        }
        
        /**
         *    Accessor for the number of test cases
         *    completed so far.
         *    @return    Number of ended cases.
         *    @public
         */
        function getTestCaseProgress() {
            return $this->_progress;
        }
    }
?>